### ISSUE TITLE
make: *** [run] Illegal instruction

### ISSUE THREAD

**Issue by allewwaly** [tristartom/sgx-emulator#1]
Hi, any instructions on how to use the sgx-emulator at https://github.com/tristartom/sgx-emulator?
I've configured a ubuntu 1404 VM using vmware and the kernel is 3.19 as the readme says, but it still failed to insmod or run the sgx module. The error is as follows:
# sudo insmod sgx.ko

insmod: ERROR: could not insert module sgx.ko: Invalid module format
# make r

TT: base:0x2b608daea000, _entry_point:0x2b608daeaf03, diff: 0xf03, args: 0x7fff02d71970
00400000-00402000 r-xp 00000000 08:01 6167990                            /home/john/sgx-emulator/bin/a.out
00601000-00602000 r--p 00001000 08:01 6167990                            /home/john/sgx-emulator/bin/a.out
00602000-00603000 rw-p 00002000 08:01 6167990                            /home/john/sgx-emulator/bin/a.out
00d07000-00d28000 rw-p 00000000 00:00 0                                  [heap]
2b608d2fc000-2b608d31f000 r-xp 00000000 08:01 4723319                    /lib/x86_64-linux-gnu/ld-2.19.so
2b608d31f000-2b608d322000 rw-p 00000000 00:00 0
2b608d32f000-2b608d332000 rw-p 00000000 00:00 0
2b608d51e000-2b608d51f000 r--p 00022000 08:01 4723319                    /lib/x86_64-linux-gnu/ld-2.19.so
2b608d51f000-2b608d520000 rw-p 00023000 08:01 4723319                    /lib/x86_64-linux-gnu/ld-2.19.so
2b608d520000-2b608d521000 rw-p 00000000 00:00 0
2b608d521000-2b608d524000 r-xp 00000000 08:01 4723311                    /lib/x86_64-linux-gnu/libdl-2.19.so
2b608d524000-2b608d723000 ---p 00003000 08:01 4723311                    /lib/x86_64-linux-gnu/libdl-2.19.so
2b608d723000-2b608d724000 r--p 00002000 08:01 4723311                    /lib/x86_64-linux-gnu/libdl-2.19.so
2b608d724000-2b608d725000 rw-p 00003000 08:01 4723311                    /lib/x86_64-linux-gnu/libdl-2.19.so
2b608d725000-2b608d8e0000 r-xp 00000000 08:01 4723322                    /lib/x86_64-linux-gnu/libc-2.19.so
2b608d8e0000-2b608dadf000 ---p 001bb000 08:01 4723322                    /lib/x86_64-linux-gnu/libc-2.19.so
2b608dadf000-2b608dae3000 r--p 001ba000 08:01 4723322                    /lib/x86_64-linux-gnu/libc-2.19.so
2b608dae3000-2b608dae5000 rw-p 001be000 08:01 4723322                    /lib/x86_64-linux-gnu/libc-2.19.so
2b608dae5000-2b608daea000 rw-p 00000000 00:00 0
2b608daea000-2b608daec000 r-xp 00000000 08:01 6167988                    /home/john/sgx-emulator/bin/enclave_foo.so
2b608daec000-2b608dceb000 ---p 00002000 08:01 6167988                    /home/john/sgx-emulator/bin/enclave_foo.so
2b608dceb000-2b608dcec000 r--p 00001000 08:01 6167988                    /home/john/sgx-emulator/bin/enclave_foo.so
2b608dcec000-2b608dced000 rw-p 00002000 08:01 6167988                    /home/john/sgx-emulator/bin/enclave_foo.so
2b608dced000-2b608ddd3000 r-xp 00000000 08:01 3932544                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
2b608ddd3000-2b608dfd2000 ---p 000e6000 08:01 3932544                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
2b608dfd2000-2b608dfda000 r--p 000e5000 08:01 3932544                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
2b608dfda000-2b608dfdc000 rw-p 000ed000 08:01 3932544                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
2b608dfdc000-2b608dff1000 rw-p 00000000 00:00 0
2b608dff1000-2b608e007000 r-xp 00000000 08:01 4722754                    /lib/x86_64-linux-gnu/libgcc_s.so.1
2b608e007000-2b608e206000 ---p 00016000 08:01 4722754                    /lib/x86_64-linux-gnu/libgcc_s.so.1
2b608e206000-2b608e207000 rw-p 00015000 08:01 4722754                    /lib/x86_64-linux-gnu/libgcc_s.so.1
2b608e207000-2b608e30c000 r-xp 00000000 08:01 4723307                    /lib/x86_64-linux-gnu/libm-2.19.so
2b608e30c000-2b608e50b000 ---p 00105000 08:01 4723307                    /lib/x86_64-linux-gnu/libm-2.19.so
2b608e50b000-2b608e50c000 r--p 00104000 08:01 4723307                    /lib/x86_64-linux-gnu/libm-2.19.so
2b608e50c000-2b608e50d000 rw-p 00105000 08:01 4723307                    /lib/x86_64-linux-gnu/libm-2.19.so
7fff02d52000-7fff02d73000 rw-p 00000000 00:00 0                          [stack]
7fff02dc0000-7fff02dc2000 r--p 00000000 00:00 0                          [vvar]
7fff02dc2000-7fff02dc4000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
note: sections in order: .text, .rodata, .bss
TT: begin of e_enter: which_enclave: 0xd07010; entry_point: 0x2b608daeaf03, rip_enter:400fb5, rt_args: 0x7fff02d71970
make: **\* [run] Illegal instruction

**Comment by tristartom** [comment]
Please read README, which states that you have to use VirtualBox to run this emulator. (At this stage VB is required, but later on we may remove this requirement.)

**Comment by tristartom** [comment]
Updates: we have shared a VB image on the internet with prebuilt software in it. Please find the link in README
