### ISSUE TITLE
insmod: error inserting 'sgx.ko': -1 Invalid module format

### ISSUE THREAD

**Issue by allewwaly** [tristartom/sgx-emulator#2]
insmod: error inserting 'sgx.ko': -1 Invalid module format
my VM configuration:
uname -a: Linux ubuntu 3.19.0-031900-generic #201504091832 SMP Thu Apr 9 17:35:46 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
the virtualization software is virtualbox 5.0.14

**Comment by tristartom** [comment]
Please checkout the prebuilt image: https://www.dropbox.com/s/z18a12m09ajw6ry/sgx-env.vdi?dl=0 .

It should be working.
